=== andrewha-dev/School-Files/Year 3/Web Programming V/Assignments/aha_C50_A02/PartA/Olympics.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 sp1 (x64) (http://www.altova.com) by Computer Science (CEGEP Heritage College) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://csdev.cegep-heritage.qc.ca/olympics" targetNamespace="http://csdev.cegep-heritage.qc.ca/olympics">
	<xs:element name="countries">
		<xs:complexType>			
			<xs:sequence>
				<xs:element ref="country" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		
	</xs:element>
	
	<xs:element name="country">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="athletes"/>
				<xs:element ref="medals"/>
				<xs:element ref="flagBearer"/>
			</xs:sequence>
			<xs:attribute name="year" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="name">
	</xs:element>
	
	<xs:element name="athletes">
	</xs:element>
	
	<xs:element name="medals">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="gold" minOccurs="0"/>
				<xs:element ref="silver" minOccurs="0"/>
				<xs:element ref="bronze" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="flagBearer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lastName"/>
				<xs:element ref="firstName"/>
			</xs:sequence>
			<xs:attribute name="sport" type="sportType"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="gold" type="xs:integer">
	</xs:element>
	
	<xs:element name="silver" type="xs:integer">
	</xs:element>
	
	<xs:element name="bronze" type="xs:integer">
	</xs:element>
	
	<xs:element name="lastName" type="xs:string">
	</xs:element>
	
	<xs:element name="firstName" type="xs:string">
	</xs:element>
	
	<xs:attribute name="year" type="xs:integer"/>
	
	<xs:attribute name="sport" type="sportType"/>
	
	<xs:simpleType name="sportType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Alpine skiing"/>
			<xs:enumeration value="Biathlon"/>
			<xs:enumeration value="Bobsleigh"/>
			<xs:enumeration value="Cross-country skiing"/>
			<xs:enumeration value="Curling"/>
			<xs:enumeration value="Figure Skating"/>
			<xs:enumeration value="Freestyle skiing"/>
			<xs:enumeration value="Ice hockey"/>
			<xs:enumeration value="Luge"/>
			<xs:enumeration value="Nordic combined"/>
			<xs:enumeration value="Short track speed skating"/>
			<xs:enumeration value="Skeleton"/>
			<xs:enumeration value="Ski jumping"/>
			<xs:enumeration value="Snowboarding"/>
			<xs:enumeration value="Speed skating"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== andrewha-dev/School-Files/Year 3/Web Programming V/Assignments/aha_C50_A02/PartA/countries.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="countries.css"?>
<!-- 
The purpose of this document is to convert a list of countries in the 2010 Winter Olympics
Andrew Ha - October 2017
-->

<countries xmlns="http://csdev.cegep-heritage.qc.ca/olympics" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://csdev.cegep-heritage.qc.ca/olympics Olympics.xsd">
	<country year="1924">
		<name>Canada</name>
		<athletes>206</athletes>
		<medals>
			<gold>14</gold>
			<silver>7</silver>
			<bronze>5</bronze>
		</medals>
		<flagBearer sport="Speed skating">
			<lastName>Hughes</lastName>
			<firstName>Clara</firstName>
		</flagBearer>
	</country>
	
	<country year="1928">
		<name>Estonia</name>
		<athletes>30</athletes>
		<medals>
			<silver>1</silver>
		</medals>
		<flagBearer sport="Biathlon">
			<lastName>Lessing</lastName>
			<firstName>Roland</firstName>
		</flagBearer>
	</country>
	
	<country year="1984">
		<name>Senegal</name>
		<athletes>1</athletes>
		<medals>
		</medals>
		<flagBearer sport="Alpine skiing">
			<lastName>Seck</lastName>
			<firstName>Leyti</firstName>
		</flagBearer>
	</country>
	
	<country year="1924">
		<name>Great Britain</name>
		<athletes>52</athletes>
		<medals>
			<gold>1</gold>
		</medals>
		<flagBearer sport="Skeleton">
			<lastName>Rudman</lastName>
			<firstName>Shelley</firstName>
		</flagBearer>
	</country>
	
	<country year="1896">
		<name>Greece</name>
		<athletes>7</athletes>
		<medals>
		</medals>
		<flagBearer sport="Biathlon">
			<lastName>Tsakiris</lastName>
			<firstName>Athanassios</firstName>
		</flagBearer>
	</country>
	
	<country year="1936">
		<name>Australia</name>
		<athletes>40</athletes>
		<medals>
			<gold>2</gold>
			<silver>1</silver>
		</medals>
		<flagBearer sport="Snowboarding">
			<lastName>Bright</lastName>
			<firstName>Torah</firstName>
		</flagBearer>
	</country>
	
	<country year="1928">
		<name>Germany</name>
		<athletes>153</athletes>
		<medals>
			<gold>10</gold>
			<silver>13</silver>
			<bronze>7</bronze>
		</medals>
		<flagBearer sport="Bobsleigh">
			<lastName>Lange</lastName>
			<firstName>Andr&#233;</firstName>
		</flagBearer>
	</country>
	
	<country year="1924">
		<name>France</name>
		<athletes>108</athletes>
		<medals>
			<gold>2</gold>
			<silver>3</silver>
			<bronze>6</bronze>
		</medals>
		<flagBearer sport="Biathlon">
			<lastName>Defrasne</lastName>
			<firstName>Vincent</firstName>
		</flagBearer>
	</country>
	
	<country year="2010">
		<name>Cayman Islands</name>
		<athletes>1</athletes>
		<medals>
		</medals>
		<flagBearer sport="Alpine skiing">
			<lastName>Travers</lastName>
			<firstName>Dow</firstName>
		</flagBearer>
	</country>	
	
	<country year="1956">
		<name>Russia</name>
		<athletes>177</athletes>
		<medals>
			<gold>3</gold>
			<silver>5</silver>
			<bronze>7</bronze>
		</medals>
		<flagBearer sport="Ice hockey">
			<lastName>Morozov</lastName>
			<firstName>Aleksey</firstName>
		</flagBearer>
	</country>
	
	<country year="1924">
		<name>Sweden</name>
		<athletes>106</athletes>
		<medals>
			<gold>5</gold>
			<silver>2</silver>
			<bronze>4</bronze>
		</medals>
		<flagBearer sport="Ice hockey">
			<lastName>Forsberg</lastName>
			<firstName>Peter</firstName>
		</flagBearer>
	</country>		
	
</countries>
