=== andrewha-dev/School-Files/Cegep Heritage/Year 3/Web Programming V/Assignments/aha_C50_A01/PartA/invoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 rel. 3 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="invoice">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="info" maxOccurs="1"/>
				<xs:element ref="client" maxOccurs="1"/>
				<xs:element ref="workRecord" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="info">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="invoiceDate"/>
				<xs:element ref="billRate"/>
			</xs:sequence>
			<xs:attribute name="invoiceNumber" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="client">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contactLastName"/>
				<xs:element ref="contactFirstName"/>
				<xs:element ref="clientStreet"/>
				<xs:element ref="clientCity"/>
				<xs:element ref="clientProvince"/>
				<xs:element ref="clientPostalCode"/>
				<xs:element ref="clientDiscount"/>
			</xs:sequence>
			<xs:attribute name="clientId" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="billedHours" type="xs:integer" />
	<xs:element name="billRate" type="xs:integer" />
	<xs:element name="contactLastName" type="xs:string" />
	<xs:element name="contactFirstName" type="xs:string" />
	<xs:element name="clientStreet" type="xs:string" />
	<xs:element name="clientProvince"  type="xs:string" />
	<xs:element name="clientPostalCode" type="xs:string" />
	<xs:element name="clientDiscount" type="xs:float" />
	<xs:element name="clientCity" type="xs:string" />
	<xs:element name="workRecord">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="billedHours"/>
				<xs:element ref="workDate"/>
				<xs:element ref="workDescription"/>
				<xs:element ref="workTypeNumber"/>
			</xs:sequence>
			<xs:attribute name="workNumber" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="workDescription" type="xs:string" />
	<xs:element name="workDate" type="xs:date" />
	<xs:element name="invoiceDate" type="xs:date" />
	<xs:element name="workTypeNumber">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="CA"/>
				<xs:enumeration value="HA"/>
				<xs:enumeration value="DA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== andrewha-dev/School-Files/Year 3/Web Programming V/Assignments/aha_C50_A01/PartA/invoice2.xml
<?xml version="1.0" encoding="UTF-8"?>
<invoice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="invoice.xsd">
	<info invoiceNumber="2">
		<invoiceDate>2017-10-21</invoiceDate>
		<billRate>60</billRate>
	</info>
	<client clientId="1">
		<contactLastName>Green</contactLastName>
		<contactFirstName>Al Ways</contactFirstName>
		<clientStreet>27 Elm St</clientStreet>
		<clientCity>Ottawa</clientCity>
		<clientProvince>ON</clientProvince>
		<clientPostalCode>K2K7Y6</clientPostalCode>
		<clientDiscount>0.10</clientDiscount>
	</client>
	<workRecord workNumber="4">
		<billedHours>1</billedHours>
		<workDate>2017-10-17</workDate>
		<workDescription>Create web domain</workDescription>
		<workTypeNumber>DA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="3">
		<billedHours>6</billedHours>
		<workDate>2017-10-16</workDate>
		<workDescription>Design site</workDescription>
		<workTypeNumber>DA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="2">
		<billedHours>8</billedHours>
		<workDate>2017-10-14</workDate>
		<workDescription>Implement Design</workDescription>
		<workTypeNumber>DA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="1">
		<billedHours>2</billedHours>
		<workDate>2017-10-12</workDate>
		<workDescription>Deploy site</workDescription>
		<workTypeNumber>DA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="5">
		<billedHours>2</billedHours>
		<workDate>2017-10-20</workDate>
		<workDescription>Follow up</workDescription>
		<workTypeNumber>HA</workTypeNumber>
	</workRecord>
</invoice>

=== andrewha-dev/School-Files/Cegep Heritage/Year 3/Web Programming V/Assignments/aha_C50_A01/PartA/invoice3.xml
<?xml version="1.0" encoding="UTF-8"?>
<invoice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="invoice.xsd">
	<info invoiceNumber="3">
		<invoiceDate>2017-10-27</invoiceDate>
		<billRate>65</billRate>
	</info>
	<client clientId="1">
		<contactLastName>Render</contactLastName>
		<contactFirstName>Sir</contactFirstName>
		<clientStreet>99 Edge Way</clientStreet>
		<clientCity>Seattle</clientCity>
		<clientProvince>WA</clientProvince>
		<clientPostalCode>34560-12</clientPostalCode>
		<clientDiscount>0.05</clientDiscount>
	</client>
	<workRecord workNumber="2">
		<billedHours>8</billedHours>
		<workDate>2017-10-19</workDate>
		<workDescription>Develop JavaScript Engine</workDescription>
		<workTypeNumber>HA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="1">
		<billedHours>4</billedHours>
		<workDate>2017-10-16</workDate>
		<workDescription>Added nodejs microservice</workDescription>
		<workTypeNumber>CA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="3">
		<billedHours>2</billedHours>
		<workDate>2017-10-19</workDate>
		<workDescription>Created new template flow</workDescription>
		<workTypeNumber>DA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="4">
		<billedHours>2</billedHours>
		<workDate>2017-10-21</workDate>
		<workDescription>Deploy working site</workDescription>
		<workTypeNumber>DA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="5">
		<billedHours>2</billedHours>
		<workDate>2017-10-23</workDate>
		<workDescription>Follow up</workDescription>
		<workTypeNumber>HA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="6">
		<billedHours>4</billedHours>
		<workDate>2017-10-26</workDate>
		<workDescription>Prepare new sprint notification</workDescription>
		<workTypeNumber>HA</workTypeNumber>
	</workRecord>
</invoice>

=== andrewha-dev/School-Files/Cegep Heritage/Year 3/Web Programming V/Assignments/aha_C50_A01/PartA/invoice.xml
<?xml version="1.0" encoding="UTF-8"?>
<invoice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="invoice.xsd">
	<info invoiceNumber="1">
		<invoiceDate>2017-10-10</invoiceDate>
		<billRate>50</billRate>
	</info>
	<client clientId="3">
		<contactLastName>Hood</contactLastName>
		<contactFirstName>Donna</contactFirstName>
		<clientStreet>74 Benton</clientStreet>
		<clientCity>Gatineau</clientCity>
		<clientProvince>QC</clientProvince>
		<clientPostalCode>J8Y6T3</clientPostalCode>
		<clientDiscount>0.05</clientDiscount>
	</client>
	<workRecord workNumber="3">
		<billedHours>1</billedHours>
		<workDate>2017-09-30</workDate>
		<workDescription>Install cable</workDescription>
		<workTypeNumber>CA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="4">
		<billedHours>2</billedHours>
		<workDate>2017-10-02</workDate>
		<workDescription>Server setup and OS installation</workDescription>
		<workTypeNumber>HA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="1">
		<billedHours>4</billedHours>
		<workDate>2017-08-31</workDate>
		<workDescription>Hub and router setup</workDescription>
		<workTypeNumber>HA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="6">
		<billedHours>2</billedHours>
		<workDate>2017-07-07</workDate>
		<workDescription>PC Repair - Bad NIC</workDescription>
		<workTypeNumber>HA</workTypeNumber>
	</workRecord>
	<workRecord workNumber="11">
		<billedHours>2</billedHours>
		<workDate>2017-10-09</workDate>
		<workDescription>New PC Setup</workDescription>
		<workTypeNumber>HA</workTypeNumber>
	</workRecord>
</invoice>
