=== andrewha-dev/School-Files/Cegep Heritage/Year 3/Web Programming V/Assignments/aha_C50_A02/PartD/invoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 rel. 3 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="invoice">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="info" maxOccurs="1"/>
				<xs:element ref="client" maxOccurs="1"/>
				<xs:element ref="work_record" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="info">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="invoice_date"/>
				<xs:element ref="bill_rate"/>
			</xs:sequence>
			<xs:attribute name="invoice_number" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="client">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Client_Name"/>
				<xs:element ref="Contact_Lastname"/>
				<xs:element ref="Contact_Firstname"/>
				<xs:element ref="Client_Street"/>
				<xs:element ref="Client_City"/>
				<xs:element ref="Client_Province"/>
				<xs:element ref="Client_Postalcode"/>
				<xs:element ref="Client_Discount"/>
			</xs:sequence>
			<xs:attribute name="Client_Id" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="billed_hours" type="xs:integer"/>
	<xs:element name="bill_rate" type="xs:integer"/>
	<xs:element name="Contact_Lastname" type="xs:string"/>
	<xs:element name="Contact_Firstname" type="xs:string"/>
	<xs:element name="Client_Street" type="xs:string"/>
	<xs:element name="Client_Province" type="xs:string"/>
	<xs:element name="Client_Postalcode" type="xs:string"/>
	<xs:element name="Client_Name" type="xs:string"/>
	<xs:element name="Client_Discount" type="xs:float"/>
	<xs:element name="Client_City" type="xs:string"/>
	<xs:element name="work_record">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="billed_hours"/>
				<xs:element ref="work_date"/>
				<xs:element ref="work_description"/>
				<xs:element ref="work_type_number"/>
			</xs:sequence>
			<xs:attribute name="work_number" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="work_description" type="xs:string"/>
	<xs:element name="work_date" type="xs:date"/>
	<xs:element name="invoice_date" type="xs:date"/>
	<xs:element name="work_type_number">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="CA"/>
				<xs:enumeration value="HA"/>
				<xs:enumeration value="DA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== andrewha-dev/School-Files/Year 3/Web Programming V/Assignments/aha_C50_A02/PartD/invoice2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./invoice.xsl"?>
<invoice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="invoice.xsd">
	<info invoice_number="2">
		<invoice_date>2016-10-21</invoice_date>
		<bill_rate>60</bill_rate>
	</info>
	<client Client_Id="1">
		<Client_Name>Terrific Tree Service</Client_Name>
		<Contact_Lastname>Green</Contact_Lastname>
		<Contact_Firstname>Al Ways</Contact_Firstname>
		<Client_Street>27 Elm St</Client_Street>
		<Client_City>Ottawa</Client_City>
		<Client_Province>ON</Client_Province>
		<Client_Postalcode>K2K7Y6</Client_Postalcode>
		<Client_Discount>0.10</Client_Discount>
	</client>
	<work_record work_number="4">
		<billed_hours>1</billed_hours>
		<work_date>2016-10-17</work_date>
		<work_description>Create web domain</work_description>
		<work_type_number>DA</work_type_number>
	</work_record>
	<work_record work_number="3">
		<billed_hours>6</billed_hours>
		<work_date>2016-10-16</work_date>
		<work_description>Design site</work_description>
		<work_type_number>DA</work_type_number>
	</work_record>
	<work_record work_number="2">
		<billed_hours>8</billed_hours>
		<work_date>2016-10-14</work_date>
		<work_description>Implement Design</work_description>
		<work_type_number>DA</work_type_number>
	</work_record>
	<work_record work_number="1">
		<billed_hours>2</billed_hours>
		<work_date>2016-10-12</work_date>
		<work_description>Deploy site</work_description>
		<work_type_number>DA</work_type_number>
	</work_record>
	<work_record work_number="5">
		<billed_hours>2</billed_hours>
		<work_date>2016-10-20</work_date>
		<work_description>Follow up</work_description>
		<work_type_number>HA</work_type_number>
	</work_record>
</invoice>

=== andrewha-dev/School-Files/Year 3/Web Programming V/Assignments/aha_C50_A02/PartD/invoice.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./invoice.xsl"?>
<invoice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./invoice.xsd">
	<info invoice_number="1">
		<invoice_date>2016-10-10</invoice_date>
		<bill_rate>50</bill_rate>
	</info>
	<client Client_Id="3">
		<Client_Name>Alden Books</Client_Name>
		<Contact_Lastname>Hood</Contact_Lastname>
		<Contact_Firstname>Donna</Contact_Firstname>
		<Client_Street>74 Benton</Client_Street>
		<Client_City>Gatineau</Client_City>
		<Client_Province>QC</Client_Province>
		<Client_Postalcode>J8Y6T3</Client_Postalcode>
		<Client_Discount>0.05</Client_Discount>
	</client>
	<work_record work_number="3">
		<billed_hours>1</billed_hours>
		<work_date>2016-09-30</work_date>
		<work_description>Install cable</work_description>
		<work_type_number>CA</work_type_number>
	</work_record>
	<work_record work_number="4">
		<billed_hours>2</billed_hours>
		<work_date>2016-10-02</work_date>
		<work_description>Server setup and OS installation</work_description>
		<work_type_number>HA</work_type_number>
	</work_record>
	<work_record work_number="1">
		<billed_hours>4</billed_hours>
		<work_date>2016-08-31</work_date>
		<work_description>Hub and router setup</work_description>
		<work_type_number>HA</work_type_number>
	</work_record>
	<work_record work_number="6">
		<billed_hours>2</billed_hours>
		<work_date>2016-07-07</work_date>
		<work_description>PC Repair - Bad NIC</work_description>
		<work_type_number>HA</work_type_number>
	</work_record>
	<work_record work_number="11">
		<billed_hours>2</billed_hours>
		<work_date>2016-10-09</work_date>
		<work_description>New PC Setup</work_description>
		<work_type_number>HA</work_type_number>
	</work_record>
</invoice>
